### ISSUE TITLE
Remove dependency on Gecko build

### ISSUE THREAD

**Issue by nox** [cpearce/gecko-media#1]
This should build out of the box, without needing a Gecko build around.

**Comment by cpearce** [comment]
There is no dependency on the Gecko build.

**Comment by rtbo** [comment]
It can build without Gecko around, but still, `import.py` imports many generated files from the gecko's object dir.
That won't scale very well. As a concrete example, an error rises if `js-config.h` was generated for a debug build and you wan't to build a release crate. (and the other way around).

This crate should not rely on any generated file, but instead generate files by itself.

**Comment by rtbo** [comment]
In fact, the `js-config.h` problem is easily solved. #3

**Comment by cpearce** [comment]
Yeah, stuff generated by Gecko's build process is an issue.

In general, I'd prefer to reduce the amount of Gecko code we need to import. So I'm planning on refactoring Gecko where possible to remove dependencies on things that its Media Stack doesn't directly need.

In the specific case of the JS headers, we typically end up pulling in these when we pull in Gecko's DOM bindings or cycle collection code, and we really do not want that outside of Firefox. But I'm OK with pulling it in for now, provided it remains a quicker path to getting something working sooner.

**Comment by nox** [comment]
As a side note, I still don't understand what all this cycle collection code is about in general in Firefox' DOM, given AFAIK we avoid all of that in Servo.

**Comment by rtbo** [comment]
I started also to work on importing new cpp files into this crate.
I could import and compile `AudioSegment.cpp`, `AudioChannelFormat.cpp` and `webaudio/AudioBlock.cpp` fairly easily with "only" less than 20 new import files. (I'll soon send a PR for it)

I then started to import `webaudio/AudioBuffer.cpp`, and that's something else. I'm at > 120 header files imported (including ones that seem really unrelated to media), and I still don't see the end of it.

It should be fairly easy to write a python script that scans gecko's source tree and output a header dependency tree of a particular source file. This would help a lot:
 - no need to wait for the next compile error to know what to import next. You have the complete list right away. It could even write a json file read by import.py and avoid a lot of hand coding.
 - having the whole graph in front of you will help to decide where to use glue code or where to refactor gecko.

**Comment by cpearce** [comment]
Please make pull requests against https://github.com/servo/gecko-media/ repo, not this repo, thanks. We need to make the servo repo the master, but I've not made time to figure out how to do that yet.

I have a Python script to generate GraphViz graphs. It's not polished, and I don't have time to clean it up (I'm traveling for the rest of the week), but I will push it to github for you.

The code for WebAudio Nodes is tightly bound to Gecko's DOM bindings, so we can't just import it as-is, as Servo has a different way of doing DOM bindings, and doesn't have a cycle collector which Gecko's DOM bindings relies on.

We'll need to refactor Gecko's WebAudio code that talks to JavaScript to ensure there's an abstraction layer between the stuff that does the processing, and the stuff that talks to JavaScript.

I was thinking that the gecko-media crate would expose some public API which Servo and Gecko's DOM bindings code could both call. We'll need abstractions like BufferAllocators etc.

The filter code that we imported from blink should be independent of the DOM bindings:
http://searchfox.org/mozilla-central/source/dom/media/webaudio/blink

So you could try importing that if you're looking to help out with WebAudio.

**Comment by cpearce** [comment]
Script to generate include graph is here:
https://github.com/cpearce/gecko-include-graph

It's not pretty.
